# Generated by Django 3.0.8 on 2020-08-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chassis_No', models.CharField(max_length=150)),
                ('Engine_No', models.CharField(max_length=150)),
                ('Description', models.CharField(max_length=50)),
                ('Dlr_Invoice_No', models.CharField(blank='True', max_length=50)),
                ('GST_Invoice', models.CharField(max_length=50)),
                ('Manufacturing_Date', models.DateField()),
                ('TM_Invoice_Date', models.DateField()),
                ('Commercial_Invoice', models.CharField(max_length=150)),
                ('Selling_Dealer', models.CharField(max_length=150)),
                ('Product', models.CharField(max_length=150)),
                ('Dealer_Purchase_Order_Price', models.CharField(max_length=150)),
                ('Product_Line', models.CharField(max_length=150)),
                ('LOB', models.CharField(max_length=150)),
                ('Parent_Product_Line', models.CharField(max_length=150)),
                ('l', models.CharField(blank=True, max_length=1150)),
            ],
        ),
    ]
