# Generated by Django 3.0.8 on 2020-08-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='l',
        ),
        migrations.AlterField(
            model_name='stock',
            name='Manufacturing_Date',
            field=models.DateField(editable=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='TM_Invoice_Date',
            field=models.DateField(editable=False),
        ),
    ]
