# Generated by Django 3.0.8 on 2020-08-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20200801_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='Manufacturing_Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='TM_Invoice_Date',
            field=models.DateField(),
        ),
    ]
